### ISSUE TITLE
new sql for pgbouncer 1.9.0

### ISSUE THREAD

**Issue by MichaelDBA** [davidfetter/pgbouncer_wrapper#1]
Hi David,

Attached is a new sql file that works for pgbouncer 1.9.0.  I had to change the extension from .sql to .txt since it prevented me from uploading it.
[pgbouncer_wrapper--1.9.0.txt](https://github.com/davidfetter/pgbouncer_wrapper/files/2562905/pgbouncer_wrapper--1.9.0.txt)

Ha, I can't even type correctly!  title should be 1.9.0 not 9.1.0

**Comment by davidfetter** [comment]
Sorry I missed this earlier. I'm merging it right now.

**Comment by davidfetter** [comment]
Changes have been merged. I am not attempting to support older versions of pgbouncer.
