### ISSUE TITLE
New columns for version 1.18

### ISSUE THREAD

**Issue by MichaelDBA** [davidfetter/pgbouncer_wrapper#11]
active_sockets --> application_name text (right after the tls column and before the recv_pos column)
comment --> A string containing the application_name set on the linked client connection, or empty if this is not set, or if there is no linked connection.

clients --> application_name text (last column, right after tls column)

-- see my view below where --v18 comment is:
CREATE VIEW pgbouncer.pools AS
    SELECT * FROM dblink('pgbouncer', 'show pools') AS _(
        database text,
        "user" text,
        cl_active integer,
        cl_waiting integer,
        -- cl_cancel_req integer,        --v18 removed
        cl_active_cancel_req integer,  --v18
        cl_waiting_cancel_req integer, --v18
        sv_active integer,
        sv_active_cancel integer,      --v18
        sv_being_canceled integer,     --v18    
        sv_idle integer,
        sv_used integer,
        sv_tested integer,
        sv_login integer,
        maxwait integer,
        maxwait_us integer,
        pool_mode text
    );
```

remove comment on removed column above!!!!!

COMMENT ON COLUMN pgbouncer.pools."cl_active_cancel_req" IS $$Client connections that have forwarded query cancellations to the server and are waiting for the server response.$$;
COMMENT ON COLUMN pgbouncer.pools."cl_waiting_cancel_req" IS $$Client connections that have not forwarded query cancellations to the server yet.$$;
COMMENT ON COLUMN pgbouncer.pools."sv_active_cancel IS $$Server connections that are currently forwarding a cancel request.$$;
COMMENT ON COLUMN pgbouncer.pools."sv_being_canceled IS $$Servers that normally could become idle but are waiting to do so until all in-flight cancel requests have completed that were sent to cancel a query on this server.$$;

```
servers --> application_name text (last column, right after tls column)

sockets --> application_name text (after tls column)

**Comment by davidfetter** [comment]
Done!
